# Generated by Django 2.2.3 on 2019-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
