# Generated by Django 2.2.3 on 2019-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(unique=True)),
                ('account_type', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
