# Generated by Django 2.2.3 on 2019-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('account_number', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(max_length=10)),
                ('previous_amount', models.IntegerField(default=0)),
                ('current_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
