# Generated by Django 2.2.5 on 2019-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=10)),
                ('account_number', models.IntegerField(default=0)),
                ('transaction_amount', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
